### ISSUE TITLE
How to find out login and password?

### ISSUE THREAD

**Issue by MrSmitix** [twistedfall/utorrentctl#9]
Hi. I have uTorrent Web on my computer, and I need to manage it through the API. Everywhere they write about the fact that you need a username and password, but I don’t understand where to get it because there are no such items in the settings.

Found the /Users/mrsmitix/Library/Application Support/uTorrent Web/user.conf file. It has a line:
`localapi<hidden 16 characters> <hidden 40 characters> <hidden 20 characters> 2 1`
This is it? What of this what?

I would be very grateful for any help.

MacOS Mojave 10.14.6

**Comment by twistedfall** [comment]
I've stopped using µTorrent quite a while ago so my knowledge here is quite limited, is µTorrent Web a kind of the new web ui for the same engine or is it something completely different? In any case I suggest checking the settings, the credentials are usually set somewhere there. Also the utorrenctl hasn't been maintained for a while so it might not support some newer version of the API if it's used in µTorrent Web.
